### ISSUE TITLE
"Internet" is spelled incorrectly on top nav and bottom of page

### ISSUE THREAD

**Issue by martinezeli** [ObsequiousEmu/CMSC495-GamesDBApp#1]
Currently shows "Intenet" and should be "Internet"

**Comment by ObsequiousEmu** [comment]
D'oh. Fixed.

**Comment by martinezeli** [comment]
Bottom of page is still spelled incorrectly

**Comment by martinezeli** [comment]
top nav was fixed, but renamed it to "GamesDB" for consistency as well as did the same for the bottom of the page.
